[2023-05-06T00:35:56.508+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:35:38.370597+00:00 [queued]>
[2023-05-06T00:35:56.518+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:35:38.370597+00:00 [queued]>
[2023-05-06T00:35:56.519+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-06T00:35:56.530+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): machine_learning_task> on 2023-05-06 00:35:38.370597+00:00
[2023-05-06T00:35:56.541+0000] {standard_task_runner.py:57} INFO - Started process 11371 to run task
[2023-05-06T00:35:56.546+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'machine_learning_task', 'manual__2023-05-06T00:35:38.370597+00:00', '--job-id', '690', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp_fhf1nso']
[2023-05-06T00:35:56.547+0000] {standard_task_runner.py:85} INFO - Job 690: Subtask machine_learning_task
[2023-05-06T00:35:56.599+0000] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:35:38.370597+00:00 [running]> on host 29d8848a13b4
[2023-05-06T00:35:56.684+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lequanghop844@gmail.com' AIRFLOW_CTX_DAG_OWNER='Felix Le' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='machine_learning_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-06T00:35:38.370597+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-06T00:35:38.370597+00:00'
[2023-05-06T00:35:56.883+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:776: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-05-06T00:35:56.884+0000] {logging_mixin.py:149} INFO - Fitting 3 folds for each of 1 candidates, totalling 3 fits
[2023-05-06T00:36:17.039+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 16s
[2023-05-06T00:36:17.090+0000] {logging_mixin.py:149} INFO - 39/92 [===========>..................] - ETA: 0s 
[2023-05-06T00:36:17.141+0000] {logging_mixin.py:149} INFO - 77/92 [========================>.....] - ETA: 0s
[2023-05-06T00:36:17.174+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 1ms/step
[2023-05-06T00:36:17.216+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  20.3s
[2023-05-06T00:36:37.786+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 13s
[2023-05-06T00:36:37.837+0000] {logging_mixin.py:149} INFO - 38/92 [===========>..................] - ETA: 0s 
[2023-05-06T00:36:37.888+0000] {logging_mixin.py:149} INFO - 78/92 [========================>.....] - ETA: 0s
[2023-05-06T00:36:37.907+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 1ms/step
[2023-05-06T00:36:37.918+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  20.7s
[2023-05-06T00:36:57.987+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 15s
[2023-05-06T00:36:58.037+0000] {logging_mixin.py:149} INFO - 36/92 [==========>...................] - ETA: 0s 
[2023-05-06T00:36:58.087+0000] {logging_mixin.py:149} INFO - 74/92 [=======================>......] - ETA: 0s
[2023-05-06T00:36:58.111+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 1ms/step
[2023-05-06T00:36:58.123+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  20.2s
[2023-05-06T00:37:26.816+0000] {logging_function.py:9} INFO - Grid search results: 
[2023-05-06T00:37:26.818+0000] {logging_function.py:11} INFO - Params: {'batch_size': 128, 'dropout': 0.4, 'epochs': 50, 'learning_rate': 0.0001, 'num_units': 32} - Mean test score: -0.001826370407939027, Std test score: 8.319207582859475e-05
[2023-05-06T00:37:26.820+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/fetching_best_model.py", line 50, in best_model_search
    best_model.model.save('/Users/hople/Desktop/Work_sample/dags/model/best_lstm_model.keras')
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /Users/hople/Desktop/Work_sample/dags; Permission denied
[2023-05-06T00:37:26.831+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=machine_learning_task, execution_date=20230506T003538, start_date=20230506T003556, end_date=20230506T003726
[2023-05-06T00:37:26.842+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 690 for task machine_learning_task (/Users/hople/Desktop/Work_sample/dags; Permission denied; 11371)
[2023-05-06T00:37:27.161+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-06T00:37:27.177+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
